"""add audit_events

Revision ID: 0e7e207b39f1
Revises: f037b88eda12
Create Date: 2026-01-09 02:09:03.815659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7e207b39f1'
down_revision: Union[str, Sequence[str], None] = 'f037b88eda12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CREATED', 'STATUS_CHANGED', 'TOOL_CALLED', 'TOOL_RESULT', 'POLICY_DENIED', 'EXECUTOR_HALTED', 'ERROR', name='auditeventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_job_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
