"""create jobs

Revision ID: f037b88eda12
Revises: 
Create Date: 2026-01-09 01:44:18.657877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f037b88eda12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PREPROCESSED', 'ROUTED', 'PLANNED', 'EXECUTING', 'VERIFIED', 'ACTED', 'SUCCEEDED', 'NEEDS_REVIEW', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('pipeline_id', sa.String(length=128), nullable=True),
    sa.Column('schema_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
